.TH "s_crypt" 3 "Sun Mar 1 2015" "Version 1.0" "Elcrypt" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_crypt \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBkey\fP"
.br
.ti -1c
.RI "char * \fBsrcname\fP"
.br
.ti -1c
.RI "int \fBfdsrc\fP"
.br
.ti -1c
.RI "char * \fBtargetname\fP"
.br
.ti -1c
.RI "int \fBfdtarget\fP"
.br
.ti -1c
.RI "char \fBoptodo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file elcrypto\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elcrypt from the source code\&.
